/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/extend-configurations#extend-the-webpack-config
 */

import CopyWebpackPlugin from 'copy-webpack-plugin';
import ESLintPlugin from 'eslint-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
const LiveReloadPlugin = require('webpack-livereload-plugin');
import path from 'path';
import { glob } from 'glob';
const ReplaceInFileWebpackPlugin = require('replace-in-file-webpack-plugin');

import { isWSL } from './utils';
import { DIST_DIR } from './constants';

// Support bundling nested plugins by finding all plugin.json files in src directory
// then checking for a sibling module.[jt]sx? file.
export async function getEntries(env: any): Promise<any[]> {
  const pluginsJson = await glob('panels/**/plugin.json', { absolute: true });

  const plugins = await Promise.all(
    pluginsJson.map((pluginJson) => {
      const folder = path.dirname(pluginJson);
      return glob(`${folder}/module.{ts,tsx,js,jsx}`, { absolute: true });
    })
  );

  const entries: any[] = plugins.map(entry => {
    const panel = path.relative(process.cwd(), path.dirname(entry[0])).slice('panels/'.length)

    return {
      watchOptions: isWSL() ? {
        poll: 3000,
        ignored: /node_modules/,
      } : {},
      entry: entry,
      cache: {
        type: 'filesystem',
        buildDependencies: {
          config: [__filename],
        },
      },
      context: path.join(process.cwd(), 'panels'),
      devtool: env.production ? false : 'eval-source-map',
      mode: env.production ? 'production' : 'development',
      externals: [
        'lodash',
        'jquery',
        'moment',
        'slate',
        'emotion',
        '@emotion/react',
        '@emotion/css',
        'prismjs',
        'slate-plain-serializer',
        '@grafana/slate-react',
        'react',
        'react-dom',
        'react-redux',
        'redux',
        'rxjs',
        'react-router',
        'react-router-dom',
        'd3',
        'angular',
        '@grafana/ui',
        '@grafana/runtime',
        '@grafana/data',

        // Mark legacy SDK imports as external if their name starts with the "grafana/" prefix
        (
          { request }: { request: string },
          callback: (err?: Error, result?: string|string[]|object, type?: string)=>void
        ) => {
          const prefix = 'grafana/';
          const hasPrefix = (request: string) => request.indexOf(prefix) === 0;
          const stripPrefix = (request: string) => request.substr(prefix.length);

          if (hasPrefix(request)) {
            return callback(undefined, stripPrefix(request));
          }

          callback();
        },
      ],
      output: {
        clean: {
          keep: new RegExp(`(.*?_(amd64|arm(64)?)(.exe)?|go_plugin_build_manifest)`),
        },
        filename: 'module.js',
        library: {
          type: 'amd',
        },
        path: path.resolve(process.cwd(), `${DIST_DIR}/panels/${panel}/`),
      },
      module: {
        rules: [
          {
            exclude: /(node_modules)/,
            test: /\.(js|jsx|ts|tsx)$/,
            use: {
              loader: 'babel-loader',
              options: {
                targets: "defaults",
                presets: [
                  '@babel/preset-env', '@babel/preset-typescript', '@babel/preset-react'
                ]
              }
            },
          },
          {
            test: /renderjson\.js$/,
            use: [ 'script-loader' ]
          },
          {
            test: /\.css$/,
            use: ['style-loader', 'css-loader'],
          },
          {
            test: /\.s[ac]ss$/,
            use: ['style-loader', 'css-loader', 'sass-loader'],
          }
        ],
      },
      plugins: [
        new CopyWebpackPlugin({
          patterns: [
            { from: `${panel}/README.md`, to: '.', noErrorOnMissing: true },
            { from: `${panel}/LICENSE`, to: '.', noErrorOnMissing: true },
            { from: `${panel}/CHANGELOG.md`, to: '.', noErrorOnMissing: true },
            { from: `${panel}/plugin.json`, to: '.' }, // TODO<Add an error for checking the basic structure of the repo>
          ],
        }),
        // Replace certain template-variables in the README and plugin.json
        new ReplaceInFileWebpackPlugin([
          {
            dir: DIST_DIR,
            files: [`panels/${panel}/plugin.json`],
            rules: [
              {
                search: /\%TODAY\%/g,
                replace: new Date().toISOString().substring(0, 10),
              },
            ],
          },
        ]),
        new ForkTsCheckerWebpackPlugin({
          async: Boolean(env.development),
          issue: {
            include: [{ file: '**/*.{ts,tsx}' }],
          },
          typescript: { configFile: path.join(process.cwd(), 'tsconfig.json') },
        }),
        new ESLintPlugin({
          extensions: ['.ts', '.tsx'],
          lintDirtyModulesOnly: Boolean(env.development), // don't lint on start, only lint changed files
        }),
        ...(env.development ? [new LiveReloadPlugin()] : []),
      ],

      resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
        // handle resolving "rootDir" paths
        modules: [path.resolve(process.cwd()), 'node_modules'],
        unsafeCache: true,
      },
    }
  });
  entries.push({
    entry: './plugin.json',
    context: process.cwd(),
    mode: env.production ? 'production' : 'development',
    output: {
      filename: 'null',
      path: '/dev'
    },
    plugins: [
      new CopyWebpackPlugin({
        patterns: [
          { from: `plugin.json`, to: path.resolve(process.cwd(), `${DIST_DIR}/plugin.json`) }, // TODO<Add an error for checking the basic structure of the repo>
        ],
      }),
      // Replace certain template-variables in the README and plugin.json
      new ReplaceInFileWebpackPlugin([
        {
          dir: DIST_DIR,
          files: [`plugin.json`],
          rules: [
            {
              search: /\%VERSION\%/g,
              replace: env.VERSION || '1.0.0',
            },
            {
              search: /\%TODAY\%/g,
              replace: new Date().toISOString().substring(0, 10),
            }
          ],
        },
      ])
    ]
  });

  return entries;
}

module.exports = (env: any) => getEntries(env);
