{
 "title": "Advisor Dashboard",
 "tags": [
  "Silicon",
  "Insight"
 ],
 "time": { "from": "now-1w", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_filesystem_size, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "table_definition_cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_info_schema_table_count{instance=~\"$host\"}[$interval]) or max_over_time(mysql_info_schema_table_count{instance=~\"$host\"}[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp(2^(floor(log2(mysql_info_schema_table_count{instance=~\"$host\"}))+1), 400, 2097152)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp(2^(floor(log2(mysql_info_schema_table_count{instance=~\"$host\"}))+1), 400, 2097152)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "table_open_cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Open Cache & Open Tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_variables_table_open_cache{instance=~\"$host\"}[$interval]) or max_over_time(mysql_global_variables_table_open_cache{instance=~\"$host\"}[5m])",
     "legendFormat": "Table Open Cache"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_open_tables{instance=~\"$host\"}[$interval]) or max_over_time(mysql_global_status_open_tables{instance=~\"$host\"}[5m])",
     "legendFormat": "Open Tables"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp(2^(floor(log2(max_over_time(mysql_global_status_open_tables{instance=~\"$host\"}[1w:2m])))+1), 1, 1048576)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp(2^(floor(log2(max_over_time(mysql_global_status_open_tables{instance=~\"$host\"}[1w:2m])))+1), 1, 1048576)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "innodb_log_buffer_size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InnoDB Log flushed & LSN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{instance=~\"$host\"}",
     "legendFormat": "InnoDB Log flushed"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}",
     "legendFormat": "InnoDB Long Sequence Number"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"} and on() (max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{instance=~\"$host\"})[1w:1s]) < mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"} * 0.75)) or on() (2^(floor(log2(max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{instance=~\"$host\"})[1w:1s])))+1)), 262144, 4294967295)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"} and on() (max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{instance=~\"$host\"})[1w:1s]) < mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"} * 0.75)) or on() (2^(floor(log2(max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_flush{instance=~\"$host\"})[1w:1s])))+1)), 262144, 4294967295)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "innodb_redo_log_capacity/innodb_log_file_size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Redo Log Size & Last Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"}",
     "legendFormat": "Last Checkpoint"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}",
     "legendFormat": "InnoDB Long Sequence Number"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"} or mysql_global_variables_innodb_log_file_size{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"} and on() (max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s]) < mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"} * 0.75)) or on() (2^(floor(log2(max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s])))+1) and on() (mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"})), 104857600, 137438953472) or clamp((mysql_global_variables_innodb_log_file_size{instance=~\"$host\"} and on() (max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s]) < ((mysql_global_variables_innodb_log_files_in_group{instance=~\"$host\"} * mysql_global_variables_innodb_log_file_size{instance=~\"$host\"}) or mysql_global_variables_innodb_log_file_size{instance=~\"$host\"}) * 0.75)) or on() (2^(floor(log2(max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s])))+1) / on() group_left() (mysql_global_variables_innodb_log_files_in_group{instance=~\"$host\"} or vector(1))), 1048576, scalar(549755813888 / (mysql_global_variables_innodb_log_files_in_group{instance=~\"$host\"} or vector(1))))"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"} and on() (max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s]) < mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"} * 0.75)) or on() (2^(floor(log2(max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s])))+1) and on() (mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"})), 104857600, 137438953472) or clamp((mysql_global_variables_innodb_log_file_size{instance=~\"$host\"} and on() (max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s]) < ((mysql_global_variables_innodb_log_files_in_group{instance=~\"$host\"} * mysql_global_variables_innodb_log_file_size{instance=~\"$host\"}) or mysql_global_variables_innodb_log_file_size{instance=~\"$host\"}) * 0.75)) or on() (2^(floor(log2(max_over_time((mysql_info_schema_innodb_metrics_recovery_log_lsn_current{instance=~\"$host\"}-mysql_info_schema_innodb_metrics_recovery_log_lsn_last_checkpoint{instance=~\"$host\"})[1w:1s])))+1) / on() group_left() (mysql_global_variables_innodb_log_files_in_group{instance=~\"$host\"} or vector(1))), 1048576, scalar(549755813888 / (mysql_global_variables_innodb_log_files_in_group{instance=~\"$host\"} or vector(1))))"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_redo_log_capacity{instance=~\"$host\"} or mysql_global_variables_innodb_log_file_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "innodb_io_capacity_max",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "((rate(node_disk_reads_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_reads_completed{instance=~\"$host\"}[5m])) or sum by (instance) (max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[5m]))) + ((rate(node_disk_writes_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_writes_completed{instance=~\"$host\"}[5m])) or sum by (instance) (max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[5m])))",
     "legendFormat": "Disk I/Os per second"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000 or \nsum by (instance) (max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m]))/100",
     "legendFormat": "Disk IO Utilization"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"} and on() (scalar(mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"}) == 2^(floor(log2(avg_over_time(((((rate(node_disk_reads_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_reads_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[5m]))) + ((rate(node_disk_writes_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_writes_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[5m])))) / on() group_left() (rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or irate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000 or sum by (instance) (max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m])) / 100) * 0.75 >= 0)[1w:1m])))))) or on() (2^(floor(log2(avg_over_time(((((rate(node_disk_reads_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_reads_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[5m]))) + ((rate(node_disk_writes_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_writes_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[5m])))) / on() group_left() (rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or irate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000 or sum by (instance) (max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m])) / 100) * 0.75 >= 0)[1w:1m]))))), 2000, 18446744073709551615)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"} and on() (scalar(mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"}) == 2^(floor(log2(avg_over_time(((((rate(node_disk_reads_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_reads_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[5m]))) + ((rate(node_disk_writes_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_writes_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[5m])))) / on() group_left() (rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or irate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000 or sum by (instance) (max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m])) / 100) * 0.75 >= 0)[1w:1m])))))) or on() (2^(floor(log2(avg_over_time(((((rate(node_disk_reads_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_reads_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host\"}[5m]))) + ((rate(node_disk_writes_completed{instance=~\"$host\"}[$interval]) or irate(node_disk_writes_completed{instance=~\"$host\"}[5m])) or (max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host\"}[5m])))) / on() group_left() (rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or irate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000 or sum by (instance) (max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m])) / 100) * 0.75 >= 0)[1w:1m]))))), 2000, 18446744073709551615)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "innodb_io_capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InnoDB IO Capacity Max & InnoDB IO Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"}",
     "legendFormat": "InnoDB IO Capacity Max"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_io_capacity{instance=~\"$host\"}",
     "legendFormat": "InnoDB IO Capacity"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_io_capacity{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_io_capacity{instance=~\"$host\"} and on() (mysql_global_variables_innodb_io_capacity{instance=~\"$host\"} >= mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"} * 0.5)) or (mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"} * 0.5), 100, 18446744073709551615)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_io_capacity{instance=~\"$host\"} and on() (mysql_global_variables_innodb_io_capacity{instance=~\"$host\"} >= mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"} * 0.5)) or (mysql_global_variables_innodb_io_capacity_max{instance=~\"$host\"} * 0.5), 100, 18446744073709551615)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_io_capacity{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "innodb_read_io_threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InnoDB Pending Reads & Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_engine_innodb_pending_reads{instance=~\"$host\"}[$interval]) or max_over_time(mysql_engine_innodb_pending_reads{instance=~\"$host\"}[5m])",
     "legendFormat": "InnoDB Pending Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000 or \nsum by (instance) (max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m]))/100",
     "legendFormat": "Disk IO Utilization"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_read_io_threads{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_read_io_threads{instance=~\"$host\"} and on() (max_over_time((mysql_engine_innodb_pending_reads{instance=~\"$host\"} and on() ((max(irate(node_disk_io_time_ms{instance=~\"$host\"}[5m]))/1000 or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m]))/100) or on() vector(0))[1w:2m]) < 1)) or on() (2^(floor(log2(mysql_global_variables_innodb_read_io_threads{instance=~\"$host\"}))+1)), 1, 64)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_read_io_threads{instance=~\"$host\"} and on() (max_over_time((mysql_engine_innodb_pending_reads{instance=~\"$host\"} and on() ((max(irate(node_disk_io_time_ms{instance=~\"$host\"}[5m]))/1000 or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m]))/100) or on() vector(0))[1w:2m]) < 1)) or on() (2^(floor(log2(mysql_global_variables_innodb_read_io_threads{instance=~\"$host\"}))+1)), 1, 64)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_read_io_threads{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "innodb_write_io_threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InnoDB Pending Writes & Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_engine_innodb_pending_writes{instance=~\"$host\"}[$interval]) or max_over_time(mysql_engine_innodb_pending_writes{instance=~\"$host\"}[5m])",
     "legendFormat": "InnoDB Pending Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_io_time_ms{instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_io_time_ms{instance=~\"$host\"}[5m])/1000 or \nsum by (instance) (max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m]))/100",
     "legendFormat": "Disk IO Utilization"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_write_io_threads{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_write_io_threads{instance=~\"$host\"} and on() (max_over_time((mysql_engine_innodb_pending_writes{instance=~\"$host\"} and on() ((max(irate(node_disk_io_time_ms{instance=~\"$host\"}[5m]))/1000 or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m]))/100) or on() vector(0))[1w:2m]) < 1)) or on() (2^(floor(log2(mysql_global_variables_innodb_write_io_threads{instance=~\"$host\"}))+1)), 1, 64)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_innodb_write_io_threads{instance=~\"$host\"} and on() (max_over_time((mysql_engine_innodb_pending_writes{instance=~\"$host\"} and on() ((max(irate(node_disk_io_time_ms{instance=~\"$host\"}[5m]))/1000 or max_over_time(rdsosmetrics_diskIO_util{instance=~\"$host\"}[5m]))/100) or on() vector(0))[1w:2m]) < 1)) or on() (2^(floor(log2(mysql_global_variables_innodb_write_io_threads{instance=~\"$host\"}))+1)), 1, 64)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_write_io_threads{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "binlog_cache_size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Binlog Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[$interval]))/\n(rate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[$interval])+\nrate(mysql_global_status_binlog_cache_disk_use{instance=~\"$host\"}[$interval]) > 0) or\n(irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m]))/\n(irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m])+\nirate(mysql_global_status_binlog_cache_disk_use{instance=~\"$host\"}[5m]) > 0) or on() vector(0)",
     "legendFormat": "Binlog Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_binlog_cache_size{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_binlog_cache_size{instance=~\"$host\"} and on() (avg_over_time((irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m])/(irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m])+irate(mysql_global_status_binlog_cache_disk_use{instance=~\"$host\"}[5m])))[1w:2m]) >= 0.95 or mysql_global_variables_log_bin{instance=~\"$host\"} < 1 or avg_over_time((irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m]))[1w:2m]) == 0)) or on() (mysql_global_variables_binlog_cache_size{instance=~\"$host\"} * 2), 4096, 18446744073709547520)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_binlog_cache_size{instance=~\"$host\"} and on() (avg_over_time((irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m])/(irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m])+irate(mysql_global_status_binlog_cache_disk_use{instance=~\"$host\"}[5m])))[1w:2m]) >= 0.95 or mysql_global_variables_log_bin{instance=~\"$host\"} < 1 or avg_over_time((irate(mysql_global_status_binlog_cache_use{instance=~\"$host\"}[5m]))[1w:2m]) == 0)) or on() (mysql_global_variables_binlog_cache_size{instance=~\"$host\"} * 2), 4096, 18446744073709547520)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_binlog_cache_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "binlog_stmt_cache_size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Binlog Stmt Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[$interval]))/\n(rate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[$interval])+\nrate(mysql_global_status_binlog_stmt_cache_disk_use{instance=~\"$host\"}[$interval]) > 0) or\n(irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m]))/\n(irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m])+\nirate(mysql_global_status_binlog_stmt_cache_disk_use{instance=~\"$host\"}[5m]) > 0) or on() vector(0)",
     "legendFormat": "Binlog Stmt Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 80 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"} and on() (avg_over_time((irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m])/(irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m])+irate(mysql_global_status_binlog_stmt_cache_disk_use{instance=~\"$host\"}[5m])))[1w:2m]) >= 0.95 or mysql_global_variables_log_bin{instance=~\"$host\"} < 1 or avg_over_time((irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m]))[1w:2m]) == 0)) or on() (mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"} * 2), 4096, 18446744073709547520)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 80 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp((mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"} and on() (avg_over_time((irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m])/(irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m])+irate(mysql_global_status_binlog_stmt_cache_disk_use{instance=~\"$host\"}[5m])))[1w:2m]) >= 0.95 or mysql_global_variables_log_bin{instance=~\"$host\"} < 1 or avg_over_time((irate(mysql_global_status_binlog_stmt_cache_use{instance=~\"$host\"}[5m]))[1w:2m]) == 0)) or on() (mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"} * 2), 4096, 18446744073709547520)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "tmp_table_size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temporary Table Memory Fit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(1 - (mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}/mysql_global_status_created_tmp_tables{instance=\"$host\"}))",
     "legendFormat": "Temporary Table Memory Fit Rate"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 88 },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_tmp_table_size{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "clamp(2^(floor(log2(max_over_time((mysql_global_variables_tmp_table_size{instance=\"$host\"}/(1-(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}/mysql_global_status_created_tmp_tables{instance=\"$host\"})))[1w:2m])))) or 2^(floor(log2(mysql_global_variables_tmp_table_size{instance=\"$host\"}))+1), 16777216, scalar(node_memory_MemTotal{instance=\"$host\"}*0.01 or on() vector(18446744073709551615)))"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 88 },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp(2^(floor(log2(max_over_time((mysql_global_variables_tmp_table_size{instance=\"$host\"}/(1-(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}/mysql_global_status_created_tmp_tables{instance=\"$host\"})))[1w:2m])))) or 2^(floor(log2(mysql_global_variables_tmp_table_size{instance=\"$host\"}))+1), 16777216, scalar(node_memory_MemTotal{instance=\"$host\"}*0.01 or on() vector(18446744073709551615)))"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_tmp_table_size{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "innodb_adaptive_hash_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {}
   ]
  },
  {
   "title": "AHI - Hits / (Hits + Maintenance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[$interval]) or\nirate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[5m])) / (rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{instance=~\"$host\"}[$interval])+\nrate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{instance=~\"$host\"}[$interval])+\nrate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{instance=~\"$host\"}[$interval])+\nrate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{instance=~\"$host\"}[$interval])+\nrate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{instance=~\"$host\"}[$interval])+rate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[$interval]) or\nirate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{instance=~\"$host\"}[5m])+\nirate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{instance=~\"$host\"}[5m])+\nirate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{instance=~\"$host\"}[5m])+\nirate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{instance=~\"$host\"}[5m])+\nirate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "AHI - Hits / (Hits + Maintenance)"
    }
   ]
  },
  {
   "title": "Current",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 106 },
   "format": "bool_on_off",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(vector(0) and on() (avg_over_time((irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[5m])/(irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[5m])) >= 0)[1w:2m]) < 0.5 and mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} > 0)) or on() ((mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} and on() (mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} > 0)) or on() vector(-1))"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} and on() (mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} > 0)) or on() vector(0.5)"
    }
   ]
  },
  {
   "title": "Proposed",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 106 },
   "format": "bool_on_off",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(vector(0) and on() (avg_over_time((irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[5m])/(irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_added_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_pages_removed_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_added_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_removed_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_rows_updated_total{instance=~\"$host\"}[5m])+irate(mysql_info_schema_innodb_metrics_adaptive_hash_index_adaptive_hash_searches_total{instance=~\"$host\"}[5m])) >= 0)[1w:2m]) < 0.5 and mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} > 0)) or on() ((mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} and on() (mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} > 0)) or on() vector(-1))"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} and on() (mysql_global_variables_innodb_adaptive_hash_index{instance=~\"$host\"} > 0)) or on() vector(0.5)"
    }
   ]
  },
  {
   "title": "Theoretical Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total memory usage",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "format": "bytes",
   "targets": [
    {
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * (mysql_global_variables_binlog_cache_size{instance=~\"$host\"} + mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"} + mysql_global_variables_bulk_insert_buffer_size{instance=~\"$host\"} + mysql_global_variables_join_buffer_size{instance=~\"$host\"} + mysql_global_variables_max_allowed_packet{instance=~\"$host\"} + mysql_global_variables_read_buffer_size{instance=~\"$host\"} + mysql_global_variables_read_rnd_buffer_size{instance=~\"$host\"} + mysql_global_variables_sort_buffer_size{instance=~\"$host\"} + mysql_global_variables_thread_stack{instance=~\"$host\"} + mysql_global_variables_tmp_table_size{instance=~\"$host\"}) + mysql_global_variables_slave_parallel_threads{instance=~\"$host\"} * mysql_global_variables_slave_parallel_max_queued{instance=~\"$host\"} + mysql_global_variables_binlog_file_cache_size{instance=~\"$host\"} + mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"} + mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"} + mysql_global_variables_key_buffer_size{instance=~\"$host\"} + mysql_global_variables_query_cache_size{instance=~\"$host\"} + mysql_global_variables_open_files_limit{instance=~\"$host\"} * 1024"
    },
    {
     "expr": "clamp(round((mysql_global_variables_max_connections{instance=~\"$host\"} * (mysql_global_variables_binlog_cache_size{instance=~\"$host\"} + mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"} + mysql_global_variables_bulk_insert_buffer_size{instance=~\"$host\"} + mysql_global_variables_join_buffer_size{instance=~\"$host\"} + mysql_global_variables_max_allowed_packet{instance=~\"$host\"} + mysql_global_variables_read_buffer_size{instance=~\"$host\"} + mysql_global_variables_read_rnd_buffer_size{instance=~\"$host\"} + mysql_global_variables_sort_buffer_size{instance=~\"$host\"} + mysql_global_variables_thread_stack{instance=~\"$host\"} + mysql_global_variables_tmp_table_size{instance=~\"$host\"}) + mysql_global_variables_slave_parallel_threads{instance=~\"$host\"} * mysql_global_variables_slave_parallel_max_queued{instance=~\"$host\"} + mysql_global_variables_binlog_file_cache_size{instance=~\"$host\"} + mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"} + mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"} + mysql_global_variables_key_buffer_size{instance=~\"$host\"} + mysql_global_variables_query_cache_size{instance=~\"$host\"} + mysql_global_variables_open_files_limit{instance=~\"$host\"} * 1024)/scalar(node_memory_MemTotal{instance=~\"$host\"})*100, 0.01), 0, 100)"
    }
   ]
  },
  {
   "title": "Memory usage summary",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * (mysql_global_variables_binlog_cache_size{instance=~\"$host\"} + mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"} + mysql_global_variables_bulk_insert_buffer_size{instance=~\"$host\"} + mysql_global_variables_join_buffer_size{instance=~\"$host\"} + mysql_global_variables_max_allowed_packet{instance=~\"$host\"} + mysql_global_variables_read_buffer_size{instance=~\"$host\"} + mysql_global_variables_read_rnd_buffer_size{instance=~\"$host\"} + mysql_global_variables_sort_buffer_size{instance=~\"$host\"} + mysql_global_variables_thread_stack{instance=~\"$host\"} + mysql_global_variables_tmp_table_size{instance=~\"$host\"})",
     "legendFormat": "Connection memory usage"
    },
    {
     "expr": "mysql_global_variables_slave_parallel_threads{instance=~\"$host\"} * mysql_global_variables_slave_parallel_max_queued{instance=~\"$host\"}",
     "legendFormat": "Replication memory usage"
    },
    {
     "expr": "mysql_global_variables_binlog_file_cache_size{instance=~\"$host\"} + mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"} + mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"} + mysql_global_variables_key_buffer_size{instance=~\"$host\"} + mysql_global_variables_query_cache_size{instance=~\"$host\"} + mysql_global_variables_open_files_limit{instance=~\"$host\"} * 1024",
     "legendFormat": "Global memory usage"
    }
   ]
  },
  {
   "title": "Connection memory usage",
   "type": "ssm-blockmap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_binlog_cache_size{instance=~\"$host\"}",
     "legendFormat": "binlog_cache_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_binlog_stmt_cache_size{instance=~\"$host\"}",
     "legendFormat": "binlog_stmt_cache_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_bulk_insert_buffer_size{instance=~\"$host\"}",
     "legendFormat": "bulk_insert_buffer_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_join_buffer_size{instance=~\"$host\"}",
     "legendFormat": "join_buffer_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_max_allowed_packet{instance=~\"$host\"}",
     "legendFormat": "max_allowed_packet"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_read_buffer_size{instance=~\"$host\"}",
     "legendFormat": "read_buffer_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_read_rnd_buffer_size{instance=~\"$host\"}",
     "legendFormat": "read_rnd_buffer_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_sort_buffer_size{instance=~\"$host\"}",
     "legendFormat": "sort_buffer_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_thread_stack{instance=~\"$host\"}",
     "legendFormat": "thread_stack"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{instance=~\"$host\"} * mysql_global_variables_tmp_table_size{instance=~\"$host\"}",
     "legendFormat": "tmp_table_size"
    }
   ]
  },
  {
   "title": "Replication memory usage",
   "type": "ssm-blockmap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_slave_parallel_threads{instance=~\"$host\"} * mysql_global_variables_slave_parallel_max_queued{instance=~\"$host\"}",
     "legendFormat": "slave_parallel_max_queued"
    }
   ]
  },
  {
   "title": "Global memory usage",
   "type": "ssm-blockmap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "format": "bytes",
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_binlog_file_cache_size{instance=~\"$host\"}",
     "legendFormat": "binlog_file_cache_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=~\"$host\"}",
     "legendFormat": "innodb_buffer_pool_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=~\"$host\"}",
     "legendFormat": "innodb_log_buffer_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_key_buffer_size{instance=~\"$host\"}",
     "legendFormat": "key_buffer_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_query_cache_size{instance=~\"$host\"}",
     "legendFormat": "query_cache_size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "1024 * mysql_global_variables_open_files_limit{instance=~\"$host\"}",
     "legendFormat": "open_files_limit"
    }
   ]
  }
 ]
}