{
 "title": "MongoDB ReplSet",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
   },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\", set=\"$replset\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "ReplSet State",
   "type": "stat",
   "description": "Shows the role of the selected member instance (PRIMARY or SECONDARY)",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "stat",
   "description": "Shows the number of members in the replica set",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "description": "Shows how long ago the last election occurred",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - mongodb_mongod_replset_member_election_date{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "ReplSet Lag",
   "type": "stat",
   "description": "Shows the current replication lag for the selected member",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\", set=\"$replset\"}) - min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\"} * on (name) group_left mongodb_mongod_replset_my_name{instance=~\"$host\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Storage Engine",
   "type": "stat",
   "description": "Shows the storage engine used on the instance",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_storage_engine{instance=~\"$host\"}",
     "legendFormat": "{{ engine }}"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type!~\"(command|getmore|query)\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type!~\"(command|getmore|query)\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window",
   "type": "graph",
   "description": "Shows the time range in the oplog and the oldest backed up operation.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time()-mongodb_mongod_replset_oplog_tail_timestamp{instance=~\"$host\"}",
     "legendFormat": "Now to End"
    },
    {
     "expr": "mongodb_mongod_replset_oplog_head_timestamp{instance=~\"$host\"}-mongodb_mongod_replset_oplog_tail_timestamp{instance=~\"$host\"}",
     "legendFormat": "Oplog Range"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "description": "Shows the delay between an operation occurring on the primary and that same operation getting applied on the selected member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\", set=\"$replset\"}) - min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\"} * on (name) group_left mongodb_mongod_replset_my_name{instance=~\"$host\"})) or vector(0)",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "description": "Elections happen when a primary becomes unavailable. Look at this graph over longer periods (weeks or months) to determine patterns and correlate elections with other events.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{instance=~\"$host\"}[$interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Member State Uptime",
   "type": "graph",
   "description": "Shows how long various members were in PRIMARY and SECONDARY roles",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_uptime{instance=~\"$host\"}\n* on (name) group_right(state) (max_over_time(mongodb_mongod_replset_my_name[$interval]) or max_over_time(mongodb_mongod_replset_my_name[5m]))",
     "legendFormat": "{{ instance }} - {{state}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "description": "Shows the heartbeat return times sent by the current member to other members in the replica set.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_last_heartbeat{instance=~\"$host\"}) by (name) * on (name) group_right mongodb_mongod_replset_my_name",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time",
   "type": "graph",
   "description": "This can show a correlation with the replication lag value",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_ping_ms{instance=~\"$host\"}\n* on (name) group_right(state) (max_over_time(mongodb_mongod_replset_my_name[$interval]) or max_over_time(mongodb_mongod_replset_my_name[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{instance=~\"$host\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_num_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_num_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_ops_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_ops_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{instance=~\"$host\"}[5m])",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{instance=~\"$host\"}[5m])",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{instance=~\"$host\"}[5m])",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_count{instance=~\"$host\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_size_bytes{instance=~\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_max_size_bytes{instance=~\"$host\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}