{
 "title": "MongoDB InMemory",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_storage_engine{cluster=~\"$cluster\", engine=\"inMemory\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "InMemory Data Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$host\", type=\"total\"}"
    }
   ]
  },
  {
   "title": "InMemory Max Data Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "InMemory Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "1-(max(mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$host\", type=\"total\"})/max(mongodb_mongod_wiredtiger_cache_max_bytes{instance=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "InMemory Dirty Pages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg(mongodb_mongod_wiredtiger_cache_pages{instance=~\"$host\",type=\"dirty\"})/avg(mongodb_mongod_wiredtiger_cache_pages{instance=~\"$host\",type=\"total\"})"
    }
   ]
  },
  {
   "title": "InMemory Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_transactions_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "InMemory Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_max_bytes{instance=~\"$host\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$host\", type=\"total\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "InMemory Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_cursors_total{instance=~\"$host\"}",
     "legendFormat": "Cursors"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_session_open_sessions_total{instance=~\"$host\"}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "InMemory Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_pages{instance=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "InMemory Concurrency Tickets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_concurrent_transactions_total_tickets{instance=~\"$host\"}-mongodb_mongod_wiredtiger_concurrent_transactions_out_tickets{instance=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=~\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"delete\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"delete\"}[5m])",
     "legendFormat": "repl_deleted"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"update\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"update\"}[5m])",
     "legendFormat": "repl_updated"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"insert\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{instance=~\"$host\", type=\"insert\"}[5m])",
     "legendFormat": "repl_inserted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=~\"$host\"}[5m])",
     "legendFormat": "ttl_deleted"
    }
   ]
  },
  {
   "title": "InMemory Cache Eviction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Pages / sec" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=~\"$host\",type=\"modified\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=~\"$host\",type=\"modified\"}[5m])",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=~\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=~\"$host\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$host\"}[$interval]) or irate(mongodb_mongod_extra_info_page_faults_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}