{
 "title": "MySQL Table Statistics",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Largest Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Largest Tables by Row Count",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum(mysql_info_schema_table_rows{instance=~\"$host\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Largest Tables by Size",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum(mysql_info_schema_table_size{instance=~\"$host\", component!=\"data_free\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Pie",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_info_schema_table_size{instance=~\"$host\", component!=\"data_free\"})",
     "legendFormat": "Data + Index Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mysql_info_schema_table_size{instance=~\"$host\", component=\"data_free\"})",
     "legendFormat": "Freeable Size"
    }
   ]
  },
  {
   "title": "Most Fragmented Tables by Freeable Size",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, sum(mysql_info_schema_table_size{instance=~\"$host\", component=\"data_free\"}) by (schema, table)) > 0",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Table Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "The next two graphs are available only for [Percona Server](https://www.percona.com/doc/percona-server/5.6/diagnostics/user_stats.html) and [MariaDB](https://mariadb.com/kb/en/mariadb/user-statistics/) and require `userstat` variable turned on."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rows read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Tables by Rows Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_info_schema_table_statistics_rows_read_total{instance=~\"$host\"}[$interval])>0) or topk(5, irate(mysql_info_schema_table_statistics_rows_read_total{instance=~\"$host\"}[5m])>0)",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Rows Changed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Tables by Rows Changed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_info_schema_table_statistics_rows_changed_total{instance=~\"$host\"}[$interval])>0) or topk(5, irate(mysql_info_schema_table_statistics_rows_changed_total{instance=~\"$host\"}[5m])>0)",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Auto Increment Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Tables by Auto Increment Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(10, mysql_info_schema_auto_increment_column{instance=~\"$host\"} / mysql_info_schema_auto_increment_column_max{instance=~\"$host\"})",
     "legendFormat": "{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Max Auto Increment Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(1, mysql_info_schema_auto_increment_column{instance=~\"$host\"} / mysql_info_schema_auto_increment_column_max{instance=~\"$host\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Least Used Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Least Used Indexes by Rows Read",
   "type": "ssm-filtertable-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sort(sum(mysql_info_schema_index_statistics_rows_read_total{instance=~\"$host\"}) by (schema, table, index))"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Tables By Read IO Waits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by(name) (rate(mysql_perf_schema_table_io_waits_seconds_total{instance=\"$host\", operation=\"fetch\"}[2m])) and topk(10, sum(rate(mysql_perf_schema_table_io_waits_seconds_total{instance=\"$host\", operation=\"fetch\"}[$__range]@end())) BY (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Top 10 Tables By Write IO Waits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by(name) (rate(mysql_perf_schema_table_io_waits_seconds_total{instance=\"$host\", operation=~\"update|delete|insert\"}[2m])) and topk(10, sum(rate(mysql_perf_schema_table_io_waits_seconds_total{instance=\"$host\", operation=~\"update|delete|insert\"}[$__range]@end())) BY (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}