{
 "title": "Prometheus Exporter Status",
 "tags": [
  "Insight",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$host\",job=\"linux\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=~\"$host\",job=\"linux\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=~\"$host\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_resident_memory_bytes{instance=~\"$host\",job=\"linux\"}"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_open_fds{instance=~\"$host\",job=\"linux\"}"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "time() - process_start_time_seconds{instance=~\"$host\",job=\"linux\"}"
    }
   ]
  },
  {
   "title": "Collector Scrape Successful",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "min_over_time(node_scrape_collector_success{instance=~\"$host\"}[$interval]) or min_over_time(node_scrape_collector_success{instance=~\"$host\"}[5m])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Collector Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "avg_over_time(node_scrape_collector_duration_seconds{instance=~\"$host\"}[$interval]) or avg_over_time(node_scrape_collector_duration_seconds{instance=~\"$host\"}[5m])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  { "title": "MySQLd Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$host\",job=\"mysql\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=~\"$host\",job=\"mysql\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=~\"$host\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$host\",job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$host\",job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$host\",job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "Collector Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "avg_over_time(mysql_exporter_collector_duration_seconds{instance=~\"$host\"}[$interval]) or avg_over_time(mysql_exporter_collector_duration_seconds{instance=~\"$host\"}[5m])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "MySQLd Exporter Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "max_over_time(mysql_exporter_hr_last_scrape_error{instance=~\"$host\"}[$interval]) or max_over_time(mysql_exporter_hr_last_scrape_error{instance=~\"$host\"}[5m])",
     "legendFormat": "High Resolution"
    },
    {
     "expr": "max_over_time(mysql_exporter_mr_last_scrape_error{instance=~\"$host\"}[$interval]) or max_over_time(mysql_exporter_mr_last_scrape_error{instance=~\"$host\"}[5m])",
     "legendFormat": "Medium Resolution"
    },
    {
     "expr": "max_over_time(mysql_exporter_lr_last_scrape_error{instance=~\"$host\"}[$interval]) or max_over_time(mysql_exporter_lr_last_scrape_error{instance=~\"$host\"}[5m])",
     "legendFormat": "Low Resolution"
    }
   ]
  },
  {
   "title": "Rate of  Scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "rate(mysql_exporter_hr_scrapes_total{instance=~\"$host\"}[$interval]) or irate(mysql_exporter_hr_scrapes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "High Resolution"
    },
    {
     "expr": "rate(mysql_exporter_mr_scrapes_total{instance=~\"$host\"}[$interval]) or irate(mysql_exporter_mr_scrapes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Medium Resolution"
    },
    {
     "expr": "rate(mysql_exporter_lr_scrapes_total{instance=~\"$host\"}[$interval]) or irate(mysql_exporter_lr_scrapes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Low Resolution"
    }
   ]
  },
  {
   "title": "MySQL up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "min_over_time(mysql_up{instance=~\"$host\"}[$interval]) or min_over_time(mysql_up{instance=~\"$host\"}[5m])",
     "legendFormat": "MySQL Up"
    }
   ]
  },
  {
   "title": "MongoDB Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$host\",job=\"mongodb\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=~\"$host\",job=\"mongodb\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=~\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_resident_memory_bytes{instance=~\"$host\",job=\"mongodb\"}"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_open_fds{instance=~\"$host\",job=\"mongodb\"}"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - process_start_time_seconds{instance=~\"$host\",job=\"mongodb\"}"
      }
     ]
    },
    {
     "title": "MongoDB Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(mongodb_exporter_last_scrape_duration_seconds{instance=~\"$host\"}[$interval]) or avg_over_time(mongodb_exporter_last_scrape_duration_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Avg Scrape Time"
      }
     ]
    },
    {
     "title": "MongoDB Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(mongodb_exporter_last_scrape_error{instance=~\"$host\"}[$interval]) or max_over_time(mongodb_exporter_last_scrape_error{instance=~\"$host\"}[5m])",
       "legendFormat": "MongoDB Exporter Errors"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(mongodb_exporter_scrapes_total{instance=~\"$host\"}[$interval]) or irate(mongodb_exporter_scrapes_total{instance=~\"$host\"}[5m])",
       "legendFormat": "Scrapes Rate"
      }
     ]
    },
    {
     "title": "MongoDB up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min_over_time(mongodb_up{instance=~\"$host\"}[$interval]) or min_over_time(mongodb_up{instance=~\"$host\"}[5m])",
       "legendFormat": "MongoDB Up"
      }
     ]
    }
   ]
  },
  {
   "title": "ProxySQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$host\",job=\"proxysql\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=~\"$host\",job=\"proxysql\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=~\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_resident_memory_bytes{instance=~\"$host\",job=\"proxysql\"}"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_open_fds{instance=~\"$host\",job=\"proxysql\"}"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - process_start_time_seconds{instance=~\"$host\",job=\"proxysql\"}"
      }
     ]
    },
    {
     "title": "ProxySQL Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(proxysql_exporter_last_scrape_duration_seconds{instance=~\"$host\"}[$interval]) or avg_over_time(proxysql_exporter_last_scrape_duration_seconds{instance=~\"$host\"}[5m])",
       "legendFormat": "Avg Scrape Time"
      }
     ]
    },
    {
     "title": "ProxySQL Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(proxysql_exporter_last_scrape_error{instance=~\"$host\"}[$interval]) or max_over_time(proxysql_exporter_last_scrape_error{instance=~\"$host\"}[5m])",
       "legendFormat": "ProxySQL Exporter Errors"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(proxysql_exporter_scrapes_total{instance=~\"$host\"}[$interval]) or irate(proxysql_exporter_scrapes_total{instance=~\"$host\"}[5m])",
       "legendFormat": "Scrapes Rate"
      }
     ]
    },
    {
     "title": "ProxySQL up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "min_over_time(proxysql_up{instance=~\"$host\"}[$interval]) or min_over_time(proxysql_up{instance=~\"$host\"}[5m])",
       "legendFormat": "ProxySQL Up"
      }
     ]
    }
   ]
  },
  { "title": "PostgreSQL Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(process_cpu_seconds_total{instance=~\"$host\",job=\"postgresql\"}[$interval])) by () or \nsum(irate(process_cpu_seconds_total{instance=~\"$host\",job=\"postgresql\"}[5m])) by ()) / \ncount(node_cpu{mode=\"user\", instance=~\"$host\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_resident_memory_bytes{instance=~\"$host\",job=\"postgresql\"}"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 35 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_open_fds{instance=~\"$host\",job=\"postgresql\"}"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 35 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "time() - process_start_time_seconds{instance=~\"$host\",job=\"postgresql\"}"
    }
   ]
  },
  {
   "title": "Rate of  Scrapes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "rate(pg_exporter_scrapes_total{instance=~\"$host\"}[$interval]) or \nirate(pg_exporter_scrapes_total{instance=~\"$host\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "max_over_time(pg_exporter_last_scrape_error{instance=~\"$host\"}[$interval]) or\nmax_over_time(pg_exporter_last_scrape_error{instance=~\"$host\"}[5m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Scrape Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(pg_exporter_last_scrape_duration_seconds{instance=~\"$host\"}[$interval]) or\nsum_over_time(pg_exporter_last_scrape_duration_seconds{instance=~\"$host\"}[5m])",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}